version: '3'

networks:
  default:
    driver: bridge

services:
    python:
      build: ./python
      container_name: eqe_python
      volumes:
        - ../src/:/opt/
      tty: true
    elasticsearch:
      build: ./elasticsearch
      container_name: eqe_elasticsearch
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - xpack.security.transport.ssl.enabled=false
        - ES_JAVA_OPTS=-Xmx2g -Xms2g
      volumes:
        - "./elasticsearch/data:/usr/share/elasticsearch/data"
      ports:
        - "9200:9200"
      networks:
        - default
    # # Kibana
    # kibana:
    #   image: "docker.elastic.co/kibana/kibana:7.17.3"
    #   container_name: my_kibana
    #   environment:
    #     ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    #   ulimits:
    #     memlock:
    #       soft: -1
    #       hard: -1
    #   ports:
    #     - "5601:5601"
    #   networks:
    #     - default
